basePath: /api/v1
consumes:
- application/json
definitions:
  admin.dashboardRes:
    properties:
      count:
        type: integer
    type: object
  ext.ClientError:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  model.App:
    properties:
      active:
        type: boolean
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      secret:
        type: string
      updatedAt:
        type: string
    type: object
  token.GrantReq:
    properties:
      appId:
        example: 100000
        minimum: 1
        type: integer
      appSecret:
        example: "123456"
        minLength: 1
        type: string
      email:
        example: admin@huoyijie.cn
        type: string
      password:
        example: "123456"
        minLength: 6
        type: string
    required:
    - appId
    - appSecret
    - email
    - password
    type: object
  token.GrantRes:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      refresh_token:
        type: string
      token_type:
        type: string
    type: object
  token.refreshReq:
    properties:
      access_token:
        minLength: 1
        type: string
      refresh_token:
        minLength: 1
        type: string
    required:
    - access_token
    - refresh_token
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: yijie.huo@foxmail.com
    name: huoyijie
    url: https://huoyijie.cn
  description: This is ink server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Ink API
  version: "1.0"
paths:
  /admin/apps:
    get:
      description: Show apps
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.App'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ext.ClientError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/ext.ClientError'
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Show apps
      tags:
      - app
  /admin/dashboard:
    get:
      description: Show dashboard
      parameters:
      - description: staff
        enum:
        - staff
        - user
        in: query
        name: category
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.dashboardRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ext.ClientError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ext.ClientError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/ext.ClientError'
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Show dashboard
      tags:
      - dashboard
  /token/grant:
    post:
      description: Generate token
      parameters:
      - description: request body
        in: body
        name: grantReq
        required: true
        schema:
          $ref: '#/definitions/token.GrantReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/token.GrantRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ext.ClientError'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Generate token
      tags:
      - token
  /token/refresh:
    post:
      description: Refresh token
      parameters:
      - description: request body
        in: body
        name: refreshReq
        required: true
        schema:
          $ref: '#/definitions/token.refreshReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/token.GrantRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ext.ClientError'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Refresh token
      tags:
      - token
  /token/revoke:
    post:
      description: Revoke token
      parameters:
      - description: request body
        in: body
        name: refreshReq
        required: true
        schema:
          $ref: '#/definitions/token.refreshReq'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ext.ClientError'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Revoke token
      tags:
      - token
produces:
- application/json
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
