// Auto generated by authink/orm, please do not change anything in this file
package db

import (
	"github.com/authink/ink.go/src/orm/models"
	"github.com/authink/orm/db"
	sbd "github.com/authink/sqlbuilder"
)

type app struct {
	Name sbd.Field

	Secret sbd.Field

	Active sbd.Field
}

// Tname implements db.Table.
func (*app) Tname() sbd.Table {
	return "s_apps"
}

var _ db.Table = (*app)(nil)

var App app

func init() {
	db.Bind(&App, &models.App{})
}
