// Auto generated by authink/orm, please do not change anything in this file
package db

import (
	"github.com/authink/ink.go/src/orm/models"
	"github.com/authink/orm/db"
)

type app struct {
	Name string

	Secret string

	Active string
}

// Tname implements db.Table.
func (*app) Tname() string {
	return "s_apps"
}

var _ db.Table = (*app)(nil)

var App app

func init() {
	db.Bind(&App, &models.App{})
}
