// Package db Code generated by authink/orm. DO NOT EDIT
package db

import (
	"github.com/authink/ink/src/orm/models"
	"github.com/authink/orm/db"
	sbd "github.com/authink/sqlbuilder"
)

type authTokenWithApp struct {
	authToken

	AppName sbd.Field
}

var AuthTokenWithApp authTokenWithApp

func init() {
	db.Bind(&AuthTokenWithApp, &models.AuthTokenWithApp{})
}
