// Auto generated by authink/orm, please do not change anything in this file
package db

import (
	"github.com/authink/ink.go/src/orm/models"
	"github.com/authink/orm/db"
)

type authToken struct {
	AccessToken string

	RefreshToken string

	AppId string

	AccountId string
}

// Tname implements db.Table.
func (*authToken) Tname() string {
	return "s_auth_tokens"
}

var _ db.Table = (*authToken)(nil)

var AuthToken authToken

func init() {
	db.Bind(&AuthToken, &models.AuthToken{})
}
