// Auto generated by authink/orm, please do not change anything in this file
package db

import (
	"github.com/authink/ink.go/src/orm/models"
	"github.com/authink/orm/db"
)

type authTokenWithApp struct {
	authToken

	AppName string
}

var AuthTokenWithApp authTokenWithApp

func init() {
	db.Bind(&AuthTokenWithApp, &models.AuthTokenWithApp{})
}
