// Auto generated by authink/orm, please do not change anything in this file
package db

import (
	"github.com/authink/ink/src/orm/models"
	"github.com/authink/orm/db"
	sbd "github.com/authink/sqlbuilder"
)

type department struct {
	Name sbd.Field

	OwnerId sbd.Field

	Active sbd.Field
}

// Tname implements db.Table.
func (*department) Tname() sbd.Table {
	return "s_departments"
}

var _ db.Table = (*department)(nil)

var Department department

func init() {
	db.Bind(&Department, &models.Department{})
}
