// Package db Code generated by authink/orm. DO NOT EDIT
package db

import (
	"github.com/authink/ink/src/orm/models"
	"github.com/authink/orm/db"
	sbd "github.com/authink/sqlbuilder"
)

type departmentWithOwner struct {
	department

	OwnerEmail sbd.Field
}

var DepartmentWithOwner departmentWithOwner

func init() {
	db.Bind(&DepartmentWithOwner, &models.DepartmentWithOwner{})
}
