// Auto generated by inkstone, please do not change anything in this file
package db

import (
	"github.com/authink/ink.go/src/orm/models"
	"github.com/authink/inkstone/orm/db"
)

type department struct {
	Name string

	OwnerId string

	Active string
}

// Tname implements db.Table.
func (*department) Tname() string {
	return "s_departments"
}

var _ db.Table = (*department)(nil)

var Department department

func init() {
	db.Bind(&Department, &models.Department{})
}
