// Package db Code generated by authink/orm. DO NOT EDIT
package db

import (
	"github.com/authink/ink/src/orm/models"
	"github.com/authink/orm/db"
	sbd "github.com/authink/sqlbuilder"
)

type deptStaff struct {
	DeptId sbd.Field

	StaffId sbd.Field
}

// Tname implements db.Table.
func (*deptStaff) Tname() sbd.Table {
	return "s_dept_staffs"
}

var _ db.Table = (*deptStaff)(nil)

var DeptStaff deptStaff

func init() {
	db.Bind(&DeptStaff, &models.DeptStaff{})
}
