// Package db Code generated by authink/orm. DO NOT EDIT
package db

import (
	"github.com/authink/ink/src/orm/models"
	"github.com/authink/orm/db"
	sbd "github.com/authink/sqlbuilder"
)

type deptLevel struct {
	DeptId sbd.Field

	SubDeptId sbd.Field
}

// Tname implements db.Table.
func (*deptLevel) Tname() sbd.Table {
	return "s_dept_levels"
}

var _ db.Table = (*deptLevel)(nil)

var DeptLevel deptLevel

func init() {
	db.Bind(&DeptLevel, &models.DeptLevel{})
}
