// Auto generated by authink/orm, please do not change anything in this file
package db

import (
	"github.com/authink/ink.go/src/orm/models"
	"github.com/authink/orm/db"
	sbd "github.com/authink/sqlbuilder"
)

type groupWithApp struct {
	group

	AppName sbd.Field
}

var GroupWithApp groupWithApp

func init() {
	db.Bind(&GroupWithApp, &models.GroupWithApp{})
}
