// Auto generated by authink/orm, please do not change anything in this file
package db

import (
	"github.com/authink/ink.go/src/orm/models"
	"github.com/authink/orm/db"
)

type group struct {
	Name string

	Type string

	AppId string

	Active string
}

// Tname implements db.Table.
func (*group) Tname() string {
	return "s_groups"
}

var _ db.Table = (*group)(nil)

var Group group

func init() {
	db.Bind(&Group, &models.Group{})
}
