// Package db Code generated by authink/orm. DO NOT EDIT
package db

import (
	"github.com/authink/ink/src/orm/models"
	"github.com/authink/orm/db"
	sbd "github.com/authink/sqlbuilder"
)

type groupWithApp struct {
	group

	AppName sbd.Field
}

var GroupWithApp groupWithApp

func init() {
	db.Bind(&GroupWithApp, &models.GroupWithApp{})
}
