// Auto generated by authink/orm, please do not change anything in this file
package db

import (
	"github.com/authink/ink.go/src/orm/models"
	"github.com/authink/orm/db"
)

type staff struct {
	Email string

	Password string

	Phone string

	Super string

	Active string

	Departure string
}

// Tname implements db.Table.
func (*staff) Tname() string {
	return "s_staffs"
}

var _ db.Table = (*staff)(nil)

var Staff staff

func init() {
	db.Bind(&Staff, &models.Staff{})
}
