# This is a basic workflow to help you get started with Actions

name: Deploy ink to Tecent Cloud

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: prod

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout ink.go repository
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.21'
          check-latest: true
      
      - name: Build
        run: go build -o bin/ink

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          SOURCE: ${{secrets.SOURCE}}
          SCRIPT_AFTER: systemctl ink.go restart
